### ISSUE TITLE
"Player is already pearled" message doesn't render correctly

### ISSUE THREAD

**Issue by nebula161** [CivMC/ExilePearl#15]
[Maybe this issue's already been found](https://user-images.githubusercontent.com/38367311/167527557-fa2a2c2f-da1e-41af-8623-86bd7dfae2bb.png)

**Comment by wingzero54** [comment]
Are you running CivChat2? That's my first thought

**Comment by nebula161** [comment]
> Are you running CivChat2? That's my first thought
Yup
