### ISSUE TITLE
Pearling a player by command does not send them to the Nether

### ISSUE THREAD

**Issue by wingzero54** [CivMC/ExilePearl#17]
When using the command /ep exileany a player is prison pearled, but they are not send to the nether until they respawn or disconnect. They should be transported to the nether immediately

**Comment by Diet-Cola** [comment]
Do we want to kill the player on imprisonment or send them straight to nether, the cons of the latter are whole inventory transfer

**Comment by wingzero54** [comment]
Good question, I would say we want to kill them on imprisonment. Situations where this command would be used is if a pearl was freed by mistake and the player is getting manually pearled by admins. So killing them on imprisonment may be the way to go.

**Comment by Diet-Cola** [comment]
https://github.com/CivMC/ExilePearl/pull/19
