### ISSUE TITLE
Pearls go inactive despite 1 year inactive timer

### ISSUE THREAD

**Issue by wingzero54** [CivMC/ExilePearl#27]
Need to investigate further, but reports are pearls on CivMC have gone inactive despite the decay timeout being set to 1 year https://github.com/CivMC/CivDocker/blob/master/paper/config/plugins/ExilePearl/config.yml#L272. Pearls should not go inactive until it has been 1 year since the player has been online.

**Comment by Diet-Cola** [comment]
do we have a rough time scale where pearls are going inactive / can logs track this down?

**Comment by wingzero54** [comment]
Player report is that it is after about a week or two.

I believe it may be an issue with my changes to the EP config options for "decay interval" and "decay_amount" or "decay_timeout_min" and how the math is done in the code with those two things. EP has a combination of hard-coded and config-set integers, and it's possible changing the intervals has caused bad math with the hard-coded integers

**Comment by wingzero54** [comment]
Bumping this, pearls are being set to inactive after 1-2 weeks despite the pearl decay timeout being 1 year. Reminder that intended functionality was for pearls to never timeout, but setting the decay timeout to a very large number caused pearls to immediately show as inactive on first check.

**Comment by Aleksey-Terzi** [comment]
Should be fixed by PR #41
